"""add equipment and muscle relations

Revision ID: c4011cdb5030
Revises: a83b3db8cfea
Create Date: 2024-06-26 16:02:16.597745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4011cdb5030'
down_revision: Union[str, None] = 'a83b3db8cfea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_exercise_rel',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('equipment_id', 'exercise_id')
    )
    op.create_table('muscle_exercise_rel',
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('procent', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('main', 'secondary', name='muscleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.PrimaryKeyConstraint('muscle_id', 'exercise_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muscle_exercise_rel')
    op.drop_table('equipment_exercise_rel')
    # ### end Alembic commands ###
